---
- name: Install Docker
  become: yes
  package:
    name:
      - docker
      - docker-compose
    state: present

- name: Add user to Docker group
  become: yes
  user:
    name: "{{ ansible_env.USER }}"
    groups:
      - docker
    append: yes

- name: Enable Docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
