- name: Install packages
  package:
    name:
      - alsa-utils
      - arandr
      - arc-gtk-theme
      - aria2
      - autorandr
      - bc
      - bspwm
      - docker
      - docker-compose
      - dunst
      - exfatprogs
      - feh
      - firefox
      - fzf
      - git
      - glances
      - go
      - gvfs
      - helm
      - htop
      - kubectl
      - libnotify
      - light
      - maim
      - man
      - mpv
      - nnn
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - noto-fonts-extra
      - npm
      - ntfs-3g
      - papirus-icon-theme
      - pcmanfm-gtk3
      - pdfjs
      - playerctl
      - python-pipenv
      - rust
      - rust-analyzer
      - sshpass
      - sxhkd
      - terraform
      - tmux
      - translate-shell
      - tree
      - ttf-dejavu
      - unrar
      - unzip
      - vagrant
      - virtualbox
      - virtualbox-host-modules-arch
      - w3m
      - wmctrl
      - xarchiver
      - xautolock
      - xcape
      - xclip
      - xdotool
      - xorg-server
      - xorg-setxkbmap
      - xorg-xinit
      - xorg-xrandr
      - xorg-xsetroot
      - xss-lock
      - youtube-dl
      - zathura
      - zathura-pdf-mupdf
      - zip
